### ISSUE TITLE
Unable to Login to rive.app

### ISSUE THREAD

**Issue by pattobrien** [rive-app/help-center#16]
For the past two days I've tried to log into rive.app (on both web and mac os desktop app) but whenever I do, I see the login form for only a brief second before seeing the below screen. The same goes for going through the "forget password" flow.

Additionally, I've tried deleting cookies but that did not help solve the problem. Any guidance would be appreciated - thanks!

![Screenshot 2023-10-12 at 6 05 16 AM](https://github.com/rive-app/help-center/assets/12474318/100d04db-bdb2-42a8-ae35-89e8fc15c989)

**Comment by HayesGordon** [comment]
Hey @pattobrien apologies that you're running into this issue! There are a few things we can try to debug the cause.

Can you confirm if you're experiencing the same issue on https://rive.app/community/

Can you replicate the issue on a different browser?

Will you also provide some information on:
- Browser + version
- Operating System + version

**Comment by pattobrien** [comment]
Hi @HayesGordon thanks for the quick response!

I'm able to access the rest of the site just fine, but only when I go to login is there an issue.

I just tried https://rive.app/login/ on safari - which is a browser i never use - and I'm seeing an indefinite loading spinner, so I feel like this isn't a caching problem after all.

Macbook Pro - M1 Pro
macOS 13.5.2 (22G91)
Google Chrome - v 117.0.5938.149 (Official Build) (arm64)
Safari - v 16.6 (18615.3.12.11.2)

**Comment by avivian** [comment]
Hey @pattobrien. I've been looking into this with @HayesGordon. Unfortunately I can't see anything obvious that could be causing this and we haven't had any other reports of this issue.

I need to know a little more about your environment to help me debug:
* Can you confirm that you were able to access the login page before around 10th of October when you first saw this issue?
* Do you have any adblockers or similar extensions installed? Are you running any similar software/hardware (e.g a pi-hole)?
* Can you see any errors in the developer tools console when you access that page on either chrome or safari? If so could you paste a screenshot of them here.

**Comment by caudetgit** [comment]
Hi @pattobrien Would you mind starting a ticket with Support (https://rive.app/contact) so we can look up your account?

This repo isn't actually customer support, it holds the source for our Rive Guide documentation. ;)

**Comment by tree0707** [comment]
<img width="1312" height="657" alt="Image" src="https://github.com/user-attachments/assets/1df19e5f-ba64-46d0-afc7-2ede9ee28843" />
